### ISSUE TITLE
Platforms are limited to ESP8266

### ISSUE THREAD

**Issue by dmartinpro** [leifclaesson/LeifHomieLib#1]
Is it expected/desired to only have this in library.json:
"platforms": "espressif8266",

**Comment by PatMan6889** [comment]
It is not working with ESP32 when you use PlatformiO.
@leifclaesson Please change to
"platforms": ["espressif32", "espressif8266"],
Many thanks!

**Comment by leifclaesson** [comment]
Thanks, guys! Fixed.
